### PR TITLE
incident similarity instructions

### PR DESCRIPTION
**Pull request by doormat18**
Adding instructions for incident similarity for AI manager.

### CODE REVIEW

**Comment by doormat18** [comment]
@dthiesse you think you can get to this build fail today?

**Comment by dthiesse** [comment]
@doormat18 I'm really puzzled by your build test failure. There really are not many meaningful error messages to go by. An innocent question, since your last PR was merged and before this one, did you do steps 10 and 11 on the contribution instructions here (https://cloudpak8s.io/contribute/)? That would have synced your local and fork environments with the plugin changes that fixed the last problem. The error message you are getting that gatsby may not be installed is very puzzling to me.

**Comment by doormat18** [comment]
@dthiesse yep, I did it again here for you to see.

```
$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.

$ git pull upstream master
From https://github.com/ibm-cloud-architecture/cloudpak8s
 * branch                master     -> FETCH_HEAD
Already up to date.

$ git push origin master
Everything up-to-date
```

My local build is successful, although there are errors shown. It's the Travis CI build that is failing.

Here is my local build output.

```
$ npm run dev

> cloud-pak-playbook@1.20.1 dev C:\Users\MatDavis\github.com\doormat18\cloudpak8s
> gatsby develop

Debugger listening on ws://127.0.0.1:9229/246773a8-7d63-442b-a251-ba0093db3d5d
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.448s
warn Plugin gatsby-plugin-manifest is not compatible with your gatsby version 2.24.51 - It requires
warn Plugin gatsby-plugin-manifest is not compatible with your gatsby version 2.24.51 - It requires

 ERROR #11329

Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby node APIs.

- The plugin gatsby-plugin-manifest@2.12.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-google-analytics@2.11.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-sharp@2.14.1 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-remark-images@3.11.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-transformer-yaml@2.11.0 is using the API "unstable_shouldOnCreateNode" which was introduced in gatsby@2.24.80.
- The plugin gatsby-source-filesystem@2.11.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-mdx@1.10.0 is using the API "unstable_shouldOnCreateNode" which was introduced in gatsby@2.24.80.
- The plugin gatsby-plugin-mdx@1.10.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-sass@2.8.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-emotion@4.5.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-source-filesystem@2.11.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-source-filesystem@2.11.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-manifest@2.12.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-react-helmet@3.10.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.

Some of the following may help fix the error(s):

- npm install gatsby@^2.25.0
- Rename "unstable_shouldOnCreateNode" -> "onCreateNode"
- Rename "unstable_shouldOnCreateNode" -> "onCreateNode"

success load plugins - 17.207s
success onPreInit - 0.354s
success initialize cache - 0.006s
success copy gatsby files - 0.986s
success onPreBootstrap - 0.074s
success createSchemaCustomization - 0.007s
success Checking for changed pages - 0.001s
success source and transform nodes - 5.494s
success building schema - 0.435s
success createPages - 0.001s
success Checking for changed pages - 0.001s
success createPagesStatefully - 6.111s
success update schema - 0.043s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.094s
success Build manifest and related icons - 0.444s
success onPostBootstrap - 0.972s
info bootstrap finished - 52.396s
success onPreExtractQueries - 0.001s
success extract queries from components - 2.326s
success write out requires - 0.125s
success run static queries - 0.117s - 1/1 8.56/s
success run page queries - 0.363s - 48/48 132.23/s
warn Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
⠀
You can now view cloud-pak-playbook in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 103.039s
```

**Comment by dthiesse** [comment]
Thank you @doormat18 . That is useful information. I will try to figure it out.

**Comment by dthiesse** [comment]
@doormat18 Can you try to follow the steps in "Steps to fix the error" in https://github.com/gatsbyjs/gatsby/issues/7086 in the same branch locally and push another commit with the result?

**Comment by dthiesse** [comment]
Also, @doormat18 , in the above post and also others I found when googling the problem, some people had it work when they used "yarn" for the install instead of "npm". Might be worth trying if the first steps don't work.

**Comment by doormat18** [comment]
Instead of troubleshooting this, I'm just going to clean out and restart my fork.

**Pull request closed without merging**
