### PR TITLE
site overhaul to CPs at Work

### PR DESCRIPTION
**Pull request by dthiesse**
This is the major revamp @jdiggity22 . Took out all the install content, renamed the site to "Cloud Paks at Work". Pretty much just left Richard Wilkins content there until we can find another home for it. And some CP 4 Apps generic content. Please review, approve and merge if you are happy. Thx.

### CODE REVIEW

**Comment by jdiggity22** [comment]
Ok.. @dthiesse There are a lot of changes here. I will try to pull it locally and work through it. I should be able to get to this tomorrow.

**Comment by dthiesse** [comment]
OK thanks @jdiggity22. The check failed, I think because of a syntax thing that did not cause a problem for me locally. Putting in what I think is the fix. Will keep working till the check succeeds.

**Comment by dthiesse** [comment]
Yay! The check succeeded with my change. BTW I have saved off all the content I removed, including the MCM Concepts stuff.

**Comment by dthiesse** [comment]
@jdiggity22 I'm officially off now for Christmas, but I will look for and respond to any questions or problems you have with this. Merry Christmas!

**Review by jdiggity22 — APPROVED** [review]
Great work @dthiesse ! Looks good.

**Pull request merged**
